### ISSUE TITLE
[multisig-api][Staking] Block further staking transaction while there is pending staking transaction

### ISSUE THREAD

**Issue by ChickenHarry** [aura-nw/multisig-api#82]
Currently each multisig safe can only create one multi-sig staking transaction (Delegate, Undelegate, Redelegate, Claim Reward) at a time. All function must be disabled exept:

- Manage 

- Validator filtering and searching

Refer to Docs:
https://www.notion.so/aura-network/Function-Staking-2aafd44a01584b0fa1d063299cb2d758

**Comment by hangpham23** [comment]
Verified. PASS
<img width="1440" alt="Screen Shot 2022-10-21 at 11 02 07" src="https://user-images.githubusercontent.com/102220123/197109265-e3575e4a-6ea5-47a8-a989-ad999c35d805.png">
