### ISSUE TITLE
[Aura-Safe][Address Book] file address list is still Gnosis safe

### ISSUE THREAD

**Issue by hangpham23** [aura-nw/multisig-api#88]
## Description
file address list is still Gnosis safe > should be Pysix safe
## Environment
 - Browser: Chrome
 - Wallet: Keplr
 - Safe: evmos1ssguhw28984qpajdcr5ad5e3wnvl2z77zus7yj
 - Environment: https://safe.serenity.aura.network/
   - testnet

## Steps to reproduce
 1. Go to ttps://safe.serenity.aura.network/
 2. Connect wallet
 3. Select a safe > Address book
 4. Select export
 5. See error

## Expected result
export file name should be "pysix-safe-addressbook-Y-M-D"
## Obtained result
<img width="500" alt="Screen Shot 2022-08-15 at 15 56 18" src="https://user-images.githubusercontent.com/102220123/184606846-deb31b44-2fd7-421a-99b7-8daf0ad18c83.png">

**Comment by ntatfff** [comment]
Verified PASS on serenity (18/08/2022)
![image](https://user-images.githubusercontent.com/24869170/185365404-c06c29d7-9847-472d-a4e2-4c209fc7fdc2.png)
![image](https://user-images.githubusercontent.com/24869170/185365467-41988786-3da6-45ce-b1c7-cc382f13956f.png)
