### ISSUE TITLE
[Aura-Safe][General] Networks' color displayed not correct

### ISSUE THREAD

**Issue by hangpham23** [aura-nw/multisig-api#89]
## Description
networks' color displayed not correct on transactions and site popup
## Environment
 - Browser: Chrome
 - Wallet: Keplr
 - Environment: https://safe.serenity.aura.network/
   - testnet

## Steps to reproduce
 1. Go to https://safe.serenity.aura.network/
 2. Connect wallet
 3. Select network
 4. Observe > see error

## Expected result
Display color correctly as selected network
## Obtained result
<img width="407" alt="Screen Shot 2022-08-15 at 16 05 24" src="https://user-images.githubusercontent.com/102220123/184609106-0c115284-e10b-44d6-ba4d-f4715766d310.png">
<img width="614" alt="Screen Shot 2022-08-15 at 16 06 23" src="https://user-images.githubusercontent.com/102220123/184609120-e6f047b6-77b3-40f9-bdf0-3d0daa1a87ea.png">
<img width="902" alt="Screen Shot 2022-08-15 at 16 07 41" src="https://user-images.githubusercontent.com/102220123/184609123-7e6dec89-b466-49a2-90a2-90684b9a36cb.png">
<img width="675" alt="Screen Shot 2022-08-15 at 16 08 23" src="https://user-images.githubusercontent.com/102220123/184609130-f6160ce0-5788-41df-b6b8-0acc0bd96d9e.png">

**Comment by ntatfff** [comment]
Verified PASS on serenity (18/08/2022)
![image](https://user-images.githubusercontent.com/24869170/185362532-e2e08cc2-4ec7-4777-a305-aa8e3d020a1c.png)
![image](https://user-images.githubusercontent.com/24869170/185364093-ed17f500-e27e-47e9-8e12-ced357cbe7eb.png)
![image](https://user-images.githubusercontent.com/24869170/185364525-aa601dcd-b286-4977-92f9-89bf70aa44cc.png)
