### ISSUE TITLE
[multsig-api][General] Update Prove Ownership message from wallet

### ISSUE THREAD

**Issue by ChickenHarry** [aura-nw/multisig-api#93]
Refer to docs:
https://aura-network.notion.site/Function-Connect-Wallet-e046d43db6cd4017aaeffdeb39be20c4

**Comment by hangpham23** [comment]
Verified. PASS 
![Screen Shot 2022-10-21 at 12 10 07](https://user-images.githubusercontent.com/102220123/197116993-27dc968a-4d73-4b67-b46e-d067cbdcf835.png)
